<?php

/* fonts/fontawesome.svg */
class __TwigTemplate_19e5ca21bd7704150a3e73389b74a1513ff85ebc30b9a969f5f02baa599507d6 extends Twig_Template
{
    private $source;

    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "fonts/fontawesome.svg"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "fonts/fontawesome.svg"));

        // line 1
        echo "<?xml version=\"1.0\" standalone=\"no\"?>
<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\" >
<svg xmlns=\"http://www.w3.org/2000/svg\">
<metadata>
This is a custom SVG font generated by IcoMoon.
<iconset grid=\"14\"></iconset>
</metadata>
<defs>
<font id=\"fontawesome\" horiz-adv-x=\"448\" >
<font-face units-per-em=\"448\" ascent=\"432\" descent=\"-16\" />
<missing-glyph horiz-adv-x=\"448\" />
<glyph unicode=\"&#xe000;\" d=\"M 221.657,407.485 ,m0.00,0.00,c 0.00,0.00 -132.984-182.838 -132.205-286.236 0.515-68.522 61.089-123.688 135.314-123.218 74.202,0.479 133.943,56.421 133.428,124.943 C 357.414,226.368 221.657,407.485 221.657,407.485 z\" horiz-adv-x=\"448.00000000000006\"  />
<glyph unicode=\"&#xf060;\" d=\"M 384.00,208.00l0.00-32.00 q0.00-13.25 -8.125-22.625t-21.125-9.375l-176.00,0.00 l 73.25-73.50q 9.50-9.00 9.50-22.50t-9.50-22.50l-18.75-19.00q-9.25-9.25 -22.50-9.25q-13.00,0.00 -22.75,9.25l-162.75,163.00q-9.25,9.25 -9.25,22.50q0.00,13.00 9.25,22.75l 162.75,162.50q 9.50,9.50 22.75,9.50q 13.00,0.00 22.50-9.50l 18.75-18.50q 9.50-9.50 9.50-22.75t-9.50-22.75l-73.25-73.25l 176.00,0.00 q 13.00,0.00 21.125-9.375 t 8.125-22.625z\" horiz-adv-x=\"384\"  />
<glyph unicode=\"&#x20;\" horiz-adv-x=\"224\" />
<glyph class=\"hidden\" unicode=\"&#xf000;\" d=\"M0,432L 448 -16L0 -16 z\" horiz-adv-x=\"0\" />
</font></defs></svg>";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "fonts/fontawesome.svg";
    }

    public function getDebugInfo()
    {
        return array (  29 => 1,);
    }

    public function getSourceContext()
    {
        return new Twig_Source("<?xml version=\"1.0\" standalone=\"no\"?>
<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\" >
<svg xmlns=\"http://www.w3.org/2000/svg\">
<metadata>
This is a custom SVG font generated by IcoMoon.
<iconset grid=\"14\"></iconset>
</metadata>
<defs>
<font id=\"fontawesome\" horiz-adv-x=\"448\" >
<font-face units-per-em=\"448\" ascent=\"432\" descent=\"-16\" />
<missing-glyph horiz-adv-x=\"448\" />
<glyph unicode=\"&#xe000;\" d=\"M 221.657,407.485 ,m0.00,0.00,c 0.00,0.00 -132.984-182.838 -132.205-286.236 0.515-68.522 61.089-123.688 135.314-123.218 74.202,0.479 133.943,56.421 133.428,124.943 C 357.414,226.368 221.657,407.485 221.657,407.485 z\" horiz-adv-x=\"448.00000000000006\"  />
<glyph unicode=\"&#xf060;\" d=\"M 384.00,208.00l0.00-32.00 q0.00-13.25 -8.125-22.625t-21.125-9.375l-176.00,0.00 l 73.25-73.50q 9.50-9.00 9.50-22.50t-9.50-22.50l-18.75-19.00q-9.25-9.25 -22.50-9.25q-13.00,0.00 -22.75,9.25l-162.75,163.00q-9.25,9.25 -9.25,22.50q0.00,13.00 9.25,22.75l 162.75,162.50q 9.50,9.50 22.75,9.50q 13.00,0.00 22.50-9.50l 18.75-18.50q 9.50-9.50 9.50-22.75t-9.50-22.75l-73.25-73.25l 176.00,0.00 q 13.00,0.00 21.125-9.375 t 8.125-22.625z\" horiz-adv-x=\"384\"  />
<glyph unicode=\"&#x20;\" horiz-adv-x=\"224\" />
<glyph class=\"hidden\" unicode=\"&#xf000;\" d=\"M0,432L 448 -16L0 -16 z\" horiz-adv-x=\"0\" />
</font></defs></svg>", "fonts/fontawesome.svg", "C:\\Ampps\\www\\YonneAutos\\YonneAutosv1\\YonneAutos\\templates\\fonts\\fontawesome.svg");
    }
}
