<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOEmDZ7s\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOEmDZ7s/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOEmDZ7s.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOEmDZ7s\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOEmDZ7s\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OEmDZ7s',
    'container.build_id' => '49d45d09',
    'container.build_time' => 1549984235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOEmDZ7s');
