<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwiU0GD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwiU0GD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHwiU0GD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHwiU0GD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHwiU0GD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HwiU0GD',
    'container.build_id' => '4a29104b',
    'container.build_time' => 1550005875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwiU0GD');
